spring.application.name=demo_mvc
# debug=true

management.endpoints.web.exposure.include=health,info,endpointun
management.info.env.enabled=true
info.application.version=1.0
info.application.description="Spring Boot avec Actuator"
info.autre="A voir"


management.endpoint.health.show-details=ALWAYS